AWSTemplateFormatVersion: '2010-09-09'
Description: TulipBroker API (Lambda + HTTP API Gateway, Python)

Parameters:
  Project:       { Type: String, Default: tulipbroker-api }
  Env:           { Type: String, Default: qa }
  CodeBucket:    { Type: String, Description: 'S3 bucket with Lambda zip' }
  CodeKey:       { Type: String, Description: 'Key of the Lambda zip in CodeBucket' }
  AllowedOrigin: { Type: String, Default: "*" }
  AppVersion:    { Type: String, Default: "0.1.0" }
  GitSha:        { Type: String, Default: "" }
  BuildTime:     { Type: String, Default: "" }
  MarketSymbol:  { Type: String, Default: "tulip" }

Resources:
  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Project}-${Env}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ApiDataAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Scan
                Resource: !GetAtt OrdersTable.Arn
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt OrdersQueue.Arn

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Project}-${Env}'
      Role: !GetAtt ApiRole.Arn
      Runtime: python3.12
      Architectures: [ arm64 ]
      Handler: handlers.main.handler
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          APP_VERSION: !Ref AppVersion
          APP_ENV: !Ref Env
          GIT_SHA: !Ref GitSha
          BUILD_TIME: !Ref BuildTime
          ORDERS_TABLE: !Ref OrdersTable
          EVENTS_FIFO_URL: !Ref OrdersQueue
          MARKET_SYMBOL: !Ref MarketSymbol

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Project}-${Env}-orders'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

  OrdersQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${Project}-${Env}-orders.fifo'
      FifoQueue: true
      ContentBasedDeduplication: false
      VisibilityTimeout: 30

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${Project}-${Env}'
      ProtocolType: HTTP
      CorsConfiguration:
        AllowHeaders: ['*']
        AllowMethods: ['GET', 'POST', 'OPTIONS']
        AllowOrigins: [!Ref AllowedOrigin]

  Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations'
      PayloadFormatVersion: '2.0'

  RouteHealth:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /health'
      Target: !Sub 'integrations/${Integration}'

  RouteConfig:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /api/config'
      Target: !Sub 'integrations/${Integration}' 

  RouteOrders:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /api/orders'
      Target: !Sub 'integrations/${Integration}'

  RouteOrdersGet:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /api/orders'
      Target: !Sub 'integrations/${Integration}'

  RoutePulse:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /api/metrics/pulse'
      Target: !Sub 'integrations/${Integration}'

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true

  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/*"

Outputs:
  ApiBaseUrl:
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
  OrdersTableName:
    Value: !Ref OrdersTable
  OrdersQueueUrl:
    Value: !Ref OrdersQueue
